### ISSUE TITLE
Allow ingesting logs by url

### ISSUE THREAD

**Issue by jgraham** [mozilla/wptview#48] opened 2016-01-01 19:02 UTC
For importing logs from e.g. treeherder it would be useful if one could specify the url to a log file rather than having to save the file locally first.

**Comment by sumith1896** [comment] 2016-01-02 19:02
I'm on this.

**Comment by udiboy1209** [comment] 2016-01-09 18:21
@Sumith1896 you still on this? Or I could take it up.

**Comment by martiansideofthemoon** [comment] 2016-01-09 18:47
@udiboy1209, I think @Sumith1896 is setting up Travis + Lints so I guess you can do this if you like :smile: unless @Sumith1896 has started working on this. Do you need some more information here?

**Comment by udiboy1209** [comment] 2016-01-09 20:05
So I researched a bit, and found `$http.get('/url')` in angular which uses xhr. But the problem is cross-domain requests aren't allowed by default in javascript. And modifying the 'Access-Control-Allow-Domain' field has seurity issues I guess. 

Anyone know any alternates or ways to mae this work?

**Comment by martiansideofthemoon** [comment] 2016-01-09 21:00
@udiboy1209 , did you try running it on a python `SimpleHTTPServer`? That seemed to work for me along with [this](http://stackoverflow.com/questions/17887189/how-to-handle-plain-text-server-response#30119263) to by pass angular `$http`'s JSON check.

**Comment by jgraham** [comment] 2016-01-09 22:51
Treeherder's raw logs have CORS set up with `Access-Control-Allow-Origin: *`, so cross domain requests will work without problems.

**Comment by udiboy1209** [comment] 2016-01-10 06:18
@jgraham Okay, did not know that. I guess this can be done now. Will get on it by today evening!

**Comment by udiboy1209** [comment] 2016-01-10 22:10
I'm stuck at trying to figure out how to use `$http` in `logcruncher.js`, becuase it has to be injested and can only run in an angular run block!

Please help!

**Comment by martiansideofthemoon** [comment] 2016-01-11 04:39
@udiboy1209 you will probably need to add the `$http` [here](https://github.com/jgraham/wptview/blob/230b54ea6755ff63b400160ed5db026bd50ad7ca/angular_scripts.js#L123) (Look at `$scope.uploadFile` to see how the file is moved to `addResultsFromLogs`). May be a condition for the "Import" button will help? Make sure that the raw file goes through [this](https://github.com/jgraham/wptview/blob/230b54ea6755ff63b400160ed5db026bd50ad7ca/logcruncher.js#L12). So you might need some way of getting the raw text, or skip the `JSON.parse` step in this function.

**Comment by martiansideofthemoon** [comment] 2016-01-26 17:40
Thank you @udiboy1209 ! This is a great contribution.. Now we can think of some form of a [Treeherder](treeherder.mozilla.org/#/jobs?repo=mozilla-inbound) integration with this done!

**Comment by martiansideofthemoon** [comment] 2016-01-27 05:00
@jgraham , I am getting the error @udiboy1209 was facing (Access-Control-Allow-Origin) when I try to ingest via URL on [jgraham.github.io/wptview](jgraham.github.io) the first time I tried it. It has been working ever since. Does it work for you? What was the reason for weird behavior? Will close the issue if it works for you

**Comment by udiboy1209** [comment] 2016-01-27 06:56
I tried it with the test link in README, and it worked for me. Guess this needs proper debugging.

**Comment by jgraham** [comment] 2016-01-27 10:07
It depends on the configuration of the remote server. If it allows cross origin requests using CORS then this will work, if not it won't. Treeherder should allow it. Possibly this needs a better error message.

**Comment by martiansideofthemoon** [comment] 2016-01-27 19:39
@jgraham , As suggested by wlach, I think we need to file a bug on Bugzilla. This doesn't seem to be an issue with wptview

**Closed as completed** 2016-02-27 16:09 UTC
Labels: enhancement, assigned, next-version, back-end
